### ISSUE TITLE
在vscode中使用当前插件报没有这个文件或目录错误

### ISSUE THREAD

**Issue by Anlet** [aliyun/alibabacloud-api-vscode-toolkit#11]
1. 错误描述
在vscode中使用Alibaba Cloud API Toolkit插件时报（Pont 创建失败:ENOENT: no such file or directory, open 'c:\Users\zhao\AppData\Roaming\Code\User\globalStorage\alibabacloud-openapi.vscode-alicloud-api\alicloud-services\.remote\Ecs::2014-05-26.json'）错误。
2. 错误截图
![1712546344744](https://github.com/aliyun/alibabacloud-api-vscode-toolkit/assets/17976811/41abebe5-3a28-47c8-b585-8bb4a0802df2)
3. 系统版本截图
![1712549959736](https://github.com/aliyun/alibabacloud-api-vscode-toolkit/assets/17976811/acb9f38b-b2d2-4d52-8f86-b8a06c0b2c18)
4. vscode版本截图
![1712553068474](https://github.com/aliyun/alibabacloud-api-vscode-toolkit/assets/17976811/d313d3d7-49cf-48fd-98ef-53ce401ad783)
5. 尝试修复
  5.1. 手动新增该文件（Ecs::2014-05-26.json），但是它存在特殊字符在win10下没法增加对应的文件。 
  5.2. 尝试修改配置文件让其指向其他json文件，但是Alibaba Cloud API Toolkit插件没有提供修改该配置的地方。

**Comment by AaronLianS** [comment]
一样的问题，等待解决

**Comment by yini-chen** [comment]
感谢您提出的反馈，我们在本插件 0.0.8 版本中修复了这个问题，可以更新一下插件版本
