### ISSUE TITLE
windows快捷键ctrl+win+l与win10的“设置实时字幕”功能快捷键冲突

### ISSUE THREAD

**Issue by lightliu0** [aliyun/alibabacloud-api-vscode-toolkit#133]
如题

**Comment by yini-chen** [comment]
快捷键冲突可以在vscode 配置中进行修改：

1. 在已安装扩展中打开 Alibaba Cloud API Toolkit， 选择扩展键盘快捷方式
![image](https://github.com/user-attachments/assets/025a7b58-474e-4ecd-a189-edc05e286bcd)
2. 双击键绑定进行快捷键设置
![image](https://github.com/user-attachments/assets/13f22c73-41c6-4737-b870-24e77ee76169)

[Key Bindings for Visual Studio Code](https://code.visualstudio.com/docs/getstarted/keybindings)
