### ISSUE TITLE
调试 API 报错

### ISSUE THREAD

**Issue by lijiuxing1** [aliyun/alibabacloud-api-vscode-toolkit#193]
1. 错误描述
   调试 API 报错，错误码为 "InvalidAction.NotFound"
2. 错误截图
![image](https://github.com/user-attachments/assets/f0ac1e8b-7828-4637-b840-fa96766b8a0a)

3. 操作系统
![image](https://github.com/user-attachments/assets/f4854165-a69e-4c77-88c9-8cec6ae988c0)

4. 插件版本
Alibaba Cloud API Toolkit v0.0.14
5. 其它参考
使用 aliyun cli 执行命令，并且使用相同的AK配置，aliyun cli 可以执行成功
![image](https://github.com/user-attachments/assets/4ce4fefc-7932-4228-ad4a-be99a3c406d1)
![image](https://github.com/user-attachments/assets/50dd77d9-f9d7-451f-b713-c1a42f716948)

**Comment by yini-chen** [comment]
感谢反馈！问题已在 0.0.15 版本中修复，可以更新一下插件版本
